default: &default
  adapter: postgresql
  timeout: 5000

development:
  <<: *default
  database: todo_traiblazer_development

test:
  <<: *default
  database: todo_traiblazer_test

production:
  <<: *default
  database: todo_traiblazer_production
